#!/bin/bash

for f in ./R/*~; do
    rm -f $f
done

for f in ./R/*.ps; do
    rm -f $f
done

for f in ./man/*~; do
    rm -f $f
done

for f in ./man/*.ps; do
    rm -f $f
done

for f in ./inst/doc/*~; do
    rm -f $f
done

rm -rf ./inst/doc/figures

for f in ./tests/*~; do
    rm -f $f
done

rm -f ./inst/tests/figures

for f in ./tests/*.ps; do
    rm -f $f
done

for f in ./tests/*~; do
    rm -f $f
done

for f in ./src/*~; do
    rm -f $f
done


for f in ./inst/cache/*~; do
    rm -f $f
done

for f in ./inst/cache/*.Rout; do
    rm -f $f
done

for f in ./inst/cache/Rplots.ps; do
    rm -f $f
done

for f in ./inst/cache/.RData; do
    rm -f $f
done

for f in .Rbuildignore~; do
    rm -f $f
done

for f in *~; do
    rm -f $f
done

find . -name "DEADJOE" -exec rm -f {} \;

exit 0
